### ISSUE TITLE
Integrate with schedules

### ISSUE THREAD

**Issue by Milias** [truevoid-development/dagster-composable-graphs#17]
See [dagster documentation](https://docs.dagster.io/concepts/automation/schedules/automating-ops-schedules-jobs).

Idea (in the same definition as composable graph):

```yaml
apiVersion: truevoid.dev/v1alpha1
kind: ComposableGraph
metadata:
  name: example-graph
spec:
  inputs:
    value1: 2.0
    value2: 5.0
  operations:
    - name: add_and_multiply
      inputs:
        - value1
        - value2
  schedule:
    cron: 15 5 * * 1-5
    status: RUNNING
```

Alternative idea (separate):

```yaml
apiVersion: truevoid.dev/v1alpha1
kind: Schedule
metadata:
  name: example-schedule
spec:
  composedGraph:
    name: example-graph
  schedule:
    cron: 15 5 * * 1-5
    status: RUNNING
```
